version: '3.9'

services:
  auth-service:
    container_name: auth-service
    image: mirocinema/auth-service:dev
    build:
      context: ..
      dockerfile: auth-service/Dockerfile
    restart: always
    env_file:
      - .env.production.local
    expose:
      - '9101'
    volumes:
      - ../logs/auth:/var/log/service/auth
    networks:
      - mirocinema

networks:
  mirocinema:
    external: true